web:
  sites:
    - "https://pyconnect.org/2023/index.html"
    - "https://pretalx.com/pyconnect-2023/schedule/"
    - "https://pyconnect.org/2023/codigo-conducta.html"
vectordb:
  weviate:
    url: "https://pyconnect-genai-vdb-n77xb258.weaviate.network"
  openai:
    embeddings:
      model: "text-embedding-ada-002"
text:
  input_dir: "input"
  chunk_size: 1000
  chunk_overlap: 100
llm:
  openai:
    model: "gpt-3.5-turbo"
app:
  title: "üêç PyConnect 2023"
  header: "ü§ñ GenAI Assistant"
  subheader: "Este es una app creada como parte de la sesi√≥n: 'Construyendo soluciones con Generative AI para la transformaci√≥n digital '"
  greeting:
    - "Hola, gracias por participar del PyConnect 2023."
    - "Estoy aqu√≠ para ayudarte con cualquier duda o consulta que tengas sobre este grandioso evento."
    - ""
    - "Intenta preguntando: 'Que sesiones habra el s√°bado 14 de octubre?'"
  instruction: "Inserta tu mensaje aqu√≠:"
