web:
  sites:
    - "https://pyconnect.org/2023/index.html"
    - "https://pretalx.com/pyconnect-2023/schedule/"
    - "https://pyconnect.org/2023/codigo-conducta.html"
vectordb:
  weviate:
    url: "https://pyconnect-genai-vdb-n77xb258.weaviate.network"
  openai:
    embeddings:
      model: "text-embedding-ada-002"
text:
  input_dir: "input"
  chunk_size: 1000
  chunk_overlap: 100
llm:
  openai:
    model: "gpt-3.5-turbo"
app:
  page_title: "GenAI App"
  page_icon: ""
  title: " PyConnect 2023"
  header: " GenAI Assistant"
  subheader: "Este es una app creada como parte de la sesi贸n: 'Construyendo soluciones con Generative AI para la transformaci贸n digital '"
  greeting:
    - "Hola, gracias por participar del PyConnect 2023."
    - "Estoy aqu铆 para ayudarte con cualquier duda o consulta que tengas sobre este grandioso evento."
    - ""
    - "Intenta preguntando: 'Que sesiones habra el s谩bado 14 de octubre?'"
  sidebar: "Elige una de las opciones arriba"
  instruction: "Inserta tu mensaje aqu铆:"
  contact:
    title: "Informaci贸n de Contacto"
  project:
    title: "Informaci贸n del Proyecto"
